"""
Image Generation Cog
Uses Google Imagen 3 (via REST API) for AI image generation
"""

import logging
import os
import discord
from discord.ext import commands
import aiohttp
import io
import base64
import json

logger = logging.getLogger(__name__)

class ImageGenCog(commands.Cog):
    """AI Image Generation"""
    
    def __init__(self, bot):
        self.bot = bot
        self.api_key = os.environ.get("GEMINI_API_KEY")
        # Updated to use available Imagen 4.0 model
        self.api_url = "https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-preview-06-06:predict"
        
        if self.api_key:
            self.available = True
            logger.info("Image generation initialized with Google Imagen 4.0 (REST)")
        else:
            self.available = False
            logger.warning("GEMINI_API_KEY not found, image generation disabled")
    
    async def generate_image(self, prompt: str):
        """Generate image and return bytes"""
        if not self.available:
            return None
            
        try:
            # Prepare request
            url = f"{self.api_url}?key={self.api_key}"
            headers = {
                "Content-Type": "application/json"
            }
            payload = {
                "instances": [
                    {
                        "prompt": prompt
                    }
                ],
                "parameters": {
                    "sampleCount": 1,
                    "aspectRatio": "1:1"
                }
            }
            
            async with aiohttp.ClientSession() as session:
                async with session.post(url, headers=headers, json=payload) as resp:
                    if resp.status != 200:
                        error_text = await resp.text()
                        logger.error(f"Imagen API Error: {resp.status} - {error_text}")
                        return None
                    
                    result = await resp.json()
            
            # Extract image
            if "predictions" not in result or not result["predictions"]:
                return None
            
            b64_image = result["predictions"][0]["bytesBase64Encoded"]
            return base64.b64decode(b64_image)
            
        except Exception as e:
            logger.error(f"Image generation error: {e}")
            return None

    @commands.hybrid_command(name='draw', aliases=['generate', 'image', '描いて'])
    async def draw(self, ctx, *, prompt: str):
        """画像を生成します (Google Imagen 3)"""
        if not self.available:
            await ctx.send("❌ 画像生成機能が利用できません。GEMINI_API_KEYが設定されていません。")
            return
        
        status_msg = await ctx.send(f"🎨 「{prompt}」の画像を生成中... (Google Imagen 3)")
        
        image_data = await self.generate_image(prompt)
        
        if not image_data:
            await status_msg.edit(content="❌ 画像生成に失敗しました。")
            return
            
        try:
            # Create file
            file = discord.File(io.BytesIO(image_data), filename="generated_image.png")
            
            embed = discord.Embed(
                title="🎨 画像生成完了",
                description=f"**プロンプト:** {prompt}",
                color=0x00ff00
            )
            embed.set_image(url="attachment://generated_image.png")
            embed.set_footer(text="Generated by Google Imagen 4.0")
            
            try:
                await status_msg.edit(content=None, embed=embed, files=[file])
            except TypeError:
                try:
                    file = discord.File(io.BytesIO(image_data), filename="generated_image.png")
                    await status_msg.edit(content=None, embed=embed, file=file)
                except Exception:
                    await status_msg.delete()
                    file = discord.File(io.BytesIO(image_data), filename="generated_image.png")
                    await ctx.send(embed=embed, file=file)
            except Exception as e:
                logger.warning(f"Failed to edit message with image: {e}")
                await status_msg.delete()
                file = discord.File(io.BytesIO(image_data), filename="generated_image.png")
                await ctx.send(embed=embed, file=file)
            
        except Exception as e:
            logger.error(f"Image generation error: {e}")
            await status_msg.edit(content=f"❌ 画像生成中にエラーが発生しました: {str(e)}")

async def setup(bot):
    await bot.add_cog(ImageGenCog(bot))
